"""HTML报告输出器

生成包含可视化图表的独立HTML报告文件。
使用纯CSS + SVG绘制图表，不依赖外部资源，可直接离线打开。

包含的图表：
1. QPS 时序折线图（SVG）
2. 延迟分布直方图（SVG）
3. 延迟分位甘特图
4. 状态码饼图
5. 核心指标卡片
"""
from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from ..stats.aggregator import AggregatedMetrics


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<div class="container">
  <header class="header">
    <h1>📊 {title}</h1>
    <p class="subtitle">生成时间: {generated_at}</p>
  </header>

  <section class="cards">
    {summary_cards}
  </section>

  <section class="section">
    <h2>⏱️ 延迟分布</h2>
    <div class="chart-container">
      {latency_chart}
    </div>
    <div class="latency-table">
      {latency_table}
    </div>
  </section>

  <section class="section">
    <h2>📈 QPS 时序</h2>
    <div class="chart-container">
      {qps_chart}
    </div>
  </section>

  {errors_section}

  {scenario_section}

  <section class="section">
    <h2>� 按步骤统计</h2>
    <div class="steps-detail">
      {steps_detail}
    </div>
  </section>

  <section class="section">
    <h2>� 请求明细 (延迟)</h2>
    <div class="table-wrap">
      {by_name_table}
    </div>
  </section>

  {status_section}

  {parameter_section}

  <footer class="footer">
    <p>Generated by <strong>load_tester</strong> v1.0.0</p>
  </footer>
</div>
</body>
</html>"""

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
    "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
  background: #f0f2f5;
  color: #333;
  line-height: 1.6;
}
.container { max-width: 1200px; margin: 0 auto; padding: 24px; }

.header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 32px;
  border-radius: 16px;
  margin-bottom: 24px;
  box-shadow: 0 4px 20px rgba(102, 126, 234, 0.3);
}
.header h1 { font-size: 28px; margin-bottom: 8px; }
.header .subtitle { opacity: 0.9; font-size: 14px; }

.cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 16px;
  margin-bottom: 24px;
}
.card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
}
.card-label { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
.card-value { font-size: 28px; font-weight: 700; margin-top: 8px; }
.card-sub { font-size: 12px; color: #666; margin-top: 4px; }
.card.green .card-value { color: #10b981; }
.card.red .card-value { color: #ef4444; }
.card.blue .card-value { color: #3b82f6; }
.card.purple .card-value { color: #8b5cf6; }
.card.amber .card-value { color: #f59e0b; }
.card.cyan .card-value { color: #06b6d4; }

.section {
  background: white;
  border-radius: 16px;
  padding: 24px;
  margin-bottom: 24px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
}
.section h2 {
  font-size: 18px;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 2px solid #f0f2f5;
}

.chart-container { width: 100%; overflow-x: auto; }
.chart-container svg { width: 100%; max-width: 100%; height: auto; }

.latency-table { margin-top: 20px; overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
th, td {
  padding: 10px 12px;
  text-align: right;
  border-bottom: 1px solid #f0f2f5;
}
th:first-child, td:first-child { text-align: left; }
th {
  background: #f8fafc;
  font-weight: 600;
  color: #475569;
  position: sticky;
  top: 0;
}
tr:hover td { background: #f8fafc; }

.table-wrap { overflow-x: auto; }

.footer {
  text-align: center;
  color: #94a3b8;
  padding: 20px;
  font-size: 12px;
}

.good { color: #10b981; font-weight: 600; }
.warn { color: #f59e0b; font-weight: 600; }
.bad { color: #ef4444; font-weight: 600; }

.empty { text-align: center; color: #94a3b8; padding: 40px; }

.badge {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  color: white;
}
.badge.good { background: #10b981; color: white; }
.badge.warn { background: #f59e0b; color: white; }
.badge.bad { background: #ef4444; color: white; }

/* 步骤详情 */
.steps-detail { display: flex; flex-direction: column; gap: 12px; }
.step-card {
  background: white;
  border-radius: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
  overflow: hidden;
}
.step-card summary {
  list-style: none;
  cursor: pointer;
  padding: 16px 20px;
  user-select: none;
}
.step-card summary::-webkit-details-marker { display: none; }
.step-card summary:hover { background: #f8fafc; }
.step-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
}
.step-name {
  font-weight: 600;
  font-size: 15px;
  color: #1e293b;
  flex-shrink: 0;
}
.step-metrics {
  display: flex;
  gap: 20px;
  flex-wrap: wrap;
  justify-content: flex-end;
  flex: 1;
}
.step-metrics .metric {
  display: flex;
  flex-direction: column;
  align-items: center;
  min-width: 50px;
}
.step-metrics .metric strong {
  font-size: 14px;
  color: #1e293b;
  font-weight: 600;
}
.step-metrics .metric small {
  font-size: 11px;
  color: #94a3b8;
  margin-top: 2px;
}
.step-metrics .metric.status {
  font-size: 18px;
}
.step-metrics .metric.status.good { color: #10b981; }
.step-metrics .metric.status.warn { color: #f59e0b; }
.step-metrics .metric.status.bad { color: #ef4444; }

.step-body {
  padding: 0 20px 20px;
  border-top: 1px solid #f1f5f9;
}
.step-body h5 {
  margin: 16px 0 8px;
  font-size: 13px;
  color: #475569;
  font-weight: 600;
}
.step-body h5:first-child { margin-top: 16px; }

.mini-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.mini-table th, .mini-table td {
  padding: 6px 8px;
  text-align: center;
  border: 1px solid #e2e8f0;
}
.mini-table th {
  background: #f8fafc;
  font-weight: 600;
  color: #64748b;
}

.step-qps-section { margin-top: 12px; }
.step-qps-info {
  display: flex;
  gap: 20px;
  margin-bottom: 8px;
  font-size: 12px;
  color: #64748b;
}
.step-qps-info strong { color: #1e293b; }

.sparkline {
  width: 100%;
  height: 80px;
}
.sparkline-placeholder {
  text-align: center;
  color: #94a3b8;
  padding: 20px;
  font-size: 12px;
}

.step-status-codes { margin-top: 12px; }
.status-badge {
  display: inline-block;
  padding: 3px 10px;
  border-radius: 12px;
  font-size: 11px;
  background: #f1f5f9;
  color: #475569;
  margin-right: 6px;
  margin-bottom: 4px;
}
.status-badge.code-200 { background: #dcfce7; color: #166534; }
.status-badge.code-500 { background: #fee2e2; color: #991b1b; }
.status-badge.code-400, .status-badge.code-404 { background: #fef3c7; color: #92400e; }

.step-errors { margin-top: 12px; }
.step-errors ul {
  list-style: none;
  padding: 0;
  margin: 0;
}
.step-errors li {
  padding: 6px 10px;
  background: #fef2f2;
  border-radius: 6px;
  margin-bottom: 4px;
  font-size: 12px;
  color: #991b1b;
}
.step-errors .err-cnt {
  display: inline-block;
  background: #ef4444;
  color: white;
  padding: 1px 6px;
  border-radius: 8px;
  font-size: 10px;
  font-weight: 600;
  margin-right: 8px;
}
.step-errors .err-pct {
  color: #dc2626;
  float: right;
}
"""


class HtmlReporter:
    """HTML报告生成器"""

    def __init__(self):
        pass

    def report(
        self,
        metrics: AggregatedMetrics,
        output_path: Union[str, Path],
        title: str = "Load Test Report",
    ) -> None:
        """生成HTML报告并写入文件"""
        html = self._build_html(metrics, title)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

    def _build_html(self, m: AggregatedMetrics, title: str) -> str:
        # 概要卡片
        summary_cards = self._summary_cards(m)

        # 延迟图表
        latency_chart = self._build_latency_histogram(m)
        latency_table = self._latency_table(m)

        # QPS图表
        qps_chart = self._build_qps_chart(m)

        # 错误部分
        errors_section = self._errors_section(m)

        # 按步骤详细统计
        steps_detail = self._steps_detail(m)

        # 按名称分组
        by_name_table = self._by_name_table(m)

        # 状态分布
        status_section = self._status_section(m)

        # 场景级统计
        scenario_section = self._scenario_section(m)

        # 参数使用统计
        parameter_section = self._parameter_section(m)

        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return _HTML_TEMPLATE.format(
            title=title,
            generated_at=generated_at,
            css=_CSS,
            summary_cards=summary_cards,
            latency_chart=latency_chart,
            latency_table=latency_table,
            qps_chart=qps_chart,
            errors_section=errors_section,
            steps_detail=steps_detail,
            by_name_table=by_name_table,
            status_section=status_section,
            scenario_section=scenario_section,
            parameter_section=parameter_section,
        )

    def _card(self, label: str, value: str, sub: str = "", color: str = "") -> str:
        color_cls = f" {color}" if color else ""
        sub_html = f'<div class="card-sub">{sub}</div>' if sub else ""
        return f'<div class="card{color_cls}"><div class="card-label">{label}</div><div class="card-value">{value}</div>{sub_html}</div>'

    def _summary_cards(self, m: AggregatedMetrics) -> str:
        total = m.throughput.total_requests
        success = m.throughput.total_success
        errors = m.errors.total_errors
        sr = success / total if total else 1.0
        duration = m.duration_seconds

        sr_color = "green" if sr >= 0.99 else ("amber" if sr >= 0.95 else "red")
        err_color = "green" if errors == 0 else ("amber" if m.errors.error_rate < 0.05 else "red")

        cards = [
            self._card("总请求数", f"{total:,}", f"Duration: {duration:.1f}s", "blue"),
            self._card("成功率", f"{sr*100:.2f}%", f"{success:,} 成功", sr_color),
            self._card("失败数", f"{errors:,}", f"错误率: {m.errors.error_rate*100:.4f}%", err_color),
            self._card("平均QPS", f"{m.throughput.overall_qps:,.1f}", f"峰值: {m.throughput.peak_qps:,.1f}", "purple"),
            self._card("P50延迟", f"{m.overall.p50_ms:.2f}ms", f"平均: {m.overall.mean_ms:.2f}ms", "cyan"),
            self._card("P99延迟", f"{m.overall.p99_ms:.2f}ms", f"最大: {m.overall.max_ms:.2f}ms", "amber"),
        ]

        # 添加场景迭代统计卡片
        if m.scenario and m.scenario.total_iterations > 0:
            sc = m.scenario
            scene_sr = sc.success_iterations / sc.total_iterations if sc.total_iterations else 1.0
            scene_sr_color = "green" if scene_sr >= 0.99 else ("amber" if scene_sr >= 0.95 else "red")
            cards.extend([
                self._card("场景迭代", f"{sc.total_iterations:,}", f"迭代耗时 P50: {sc.latency.p50_ms:.2f}ms", "indigo"),
                self._card("迭代成功率", f"{scene_sr*100:.2f}%", f"{sc.success_iterations:,} 成功", scene_sr_color),
            ])

        return "\n".join(cards)

    def _build_latency_histogram(self, m: AggregatedMetrics) -> str:
        """绘制延迟分布直方图（SVG）"""
        snap = m.histogram_snapshot
        if not snap or not snap.buckets:
            return '<div class="empty">暂无数据</div>'

        buckets = [(bs / 1_000_000, cnt) for bs, cnt in snap.buckets if cnt > 0]
        if not buckets:
            return '<div class="empty">暂无数据</div>'

        max_count = max(c for _, c in buckets)
        max_lat = max(ms for ms, _ in buckets)
        min_lat = min(ms for ms, _ in buckets) if buckets else 0

        W, H = 900, 300
        padding_l, padding_r, padding_t, padding_b = 70, 30, 30, 60
        plot_w = W - padding_l - padding_r
        plot_h = H - padding_t - padding_b
        bar_w = max(2, plot_w / max(1, len(buckets)) - 1)

        x_ratio = plot_w / max(1e-9, (max_lat - min_lat)) if max_lat != min_lat else 1
        y_ratio = plot_h / max(1, max_count)

        # 生成柱子
        bars = []
        for i, (ms_val, cnt) in enumerate(buckets):
            x = padding_l + (ms_val - min_lat) * x_ratio if max_lat != min_lat else padding_l + i * (bar_w + 1)
            h = max(1, cnt * y_ratio)
            y = padding_t + plot_h - h
            # 颜色随高度渐变
            pct = cnt / max_count
            r = int(100 + pct * 155)
            g = int(180 - pct * 60)
            b = int(255 - pct * 100)
            color = f"rgb({r},{g},{b})"
            bars.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{h:.1f}" fill="{color}"><title>{ms_val:.2f}ms: {cnt}</title></rect>')

        # Y轴刻度
        y_ticks = []
        for i in range(5):
            y_val = max_count * i / 4
            y = padding_t + plot_h - y_val * y_ratio
            y_ticks.append(f'<line x1="{padding_l}" y1="{y:.1f}" x2="{W-padding_r}" y2="{y:.1f}" stroke="#e2e8f0" stroke-dasharray="4"/>')
            y_ticks.append(f'<text x="{padding_l-8}" y="{y+4:.1f}" text-anchor="end" fill="#64748b" font-size="11">{int(y_val)}</text>')

        # X轴刻度
        x_ticks = []
        n_ticks = 8
        for i in range(n_ticks + 1):
            ms_val = min_lat + (max_lat - min_lat) * i / n_ticks if max_lat != min_lat else min_lat
            x = padding_l + plot_w * i / n_ticks
            label = f"{ms_val:.1f}ms" if ms_val < 1000 else f"{ms_val/1000:.2f}s"
            x_ticks.append(f'<text x="{x:.1f}" y="{H-padding_b+20}" text-anchor="middle" fill="#64748b" font-size="11">{label}</text>')

        # 轴
        axes = [
            f'<line x1="{padding_l}" y1="{padding_t}" x2="{padding_l}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
            f'<line x1="{padding_l}" y1="{H-padding_b}" x2="{W-padding_r}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
        ]

        return f"""<svg viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet">
  <rect x="0" y="0" width="{W}" height="{H}" fill="white"/>
  {''.join(y_ticks)}
  {''.join(x_ticks)}
  {''.join(axes)}
  {''.join(bars)}
  <text x="{W/2}" y="{H-8}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600">延迟 (ms)</text>
  <text x="20" y="{padding_t+plot_h/2}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600" transform="rotate(-90,20,{padding_t+plot_h/2})">请求数</text>
</svg>"""

    def _latency_table(self, m: AggregatedMetrics) -> str:
        lat = m.overall
        rows = [
            ("总样本数", lat.count),
            ("最小值", f"{lat.min_ms:.3f} ms"),
            ("P50 中位数", f"{lat.p50_ms:.3f} ms"),
            ("P75", f"{lat.p75_ms:.3f} ms"),
            ("P90", f"{lat.p90_ms:.3f} ms"),
            ("P95", f"{lat.p95_ms:.3f} ms"),
            ("P99", f"{lat.p99_ms:.3f} ms"),
            ("P99.9", f"{lat.p999_ms:.3f} ms"),
            ("P99.99", f"{lat.p9999_ms:.3f} ms"),
            ("最大值", f"{lat.max_ms:.3f} ms"),
            ("平均值", f"{lat.mean_ms:.3f} ms"),
            ("标准差", f"{lat.stddev_ms:.3f} ms"),
        ]
        # 每列4个，生成3列布局
        per_col = 4
        cols = []
        for c in range((len(rows) + per_col - 1) // per_col):
            rows_slice = rows[c * per_col : (c + 1) * per_col]
            col_html = "<table><thead><tr><th>指标</th><th>值</th></tr></thead><tbody>"
            for k, v in rows_slice:
                col_html += f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>"
            col_html += "</tbody></table>"
            cols.append(col_html)
        style = f'display:grid; grid-template-columns: repeat({len(cols)}, 1fr); gap:16px;'
        return f'<div style="{style}">{"".join(cols)}</div>'

    def _build_qps_chart(self, m: AggregatedMetrics) -> str:
        """绘制QPS时序折线图（SVG）"""
        series = m.throughput.qps_series
        if not series:
            return '<div class="empty">暂无数据</div>'

        W, H = 900, 280
        padding_l, padding_r, padding_t, padding_b = 70, 30, 30, 60
        plot_w = W - padding_l - padding_r
        plot_h = H - padding_t - padding_b

        ts_list = [t for t, _ in series]
        qps_list = [q for _, q in series]
        min_ts, max_ts = min(ts_list), max(ts_list)
        max_qps = max(qps_list) if qps_list else 0
        max_qps = max_qps * 1.1 if max_qps > 0 else 1

        x_ratio = plot_w / max(1e-9, (max_ts - min_ts)) if max_ts != min_ts else 1
        y_ratio = plot_h / max(1, max_qps)

        # 生成折线点
        points = []
        for i, (ts, qps) in enumerate(series):
            x = padding_l + (ts - min_ts) * x_ratio if max_ts != min_ts else padding_l + i * plot_w / max(1, len(series) - 1)
            y = padding_t + plot_h - qps * y_ratio
            points.append((x, y))

        # 填充区域（折线下方渐变）
        if len(points) >= 2:
            fill_path = f'M {points[0][0]:.1f} {padding_t+plot_h:.1f} '
            fill_path += " ".join(f"L {x:.1f} {y:.1f}" for x, y in points)
            fill_path += f" L {points[-1][0]:.1f} {padding_t+plot_h:.1f} Z"
        else:
            fill_path = ""

        line_path = ""
        if len(points) >= 2:
            line_path = f"M {points[0][0]:.1f} {points[0][1]:.1f} "
            line_path += " ".join(f"L {x:.1f} {y:.1f}" for x, y in points[1:])

        # Y轴
        y_ticks = []
        for i in range(5):
            y_val = max_qps * i / 4
            y = padding_t + plot_h - y_val * y_ratio
            y_ticks.append(f'<line x1="{padding_l}" y1="{y:.1f}" x2="{W-padding_r}" y2="{y:.1f}" stroke="#e2e8f0" stroke-dasharray="4"/>')
            y_ticks.append(f'<text x="{padding_l-8}" y="{y+4:.1f}" text-anchor="end" fill="#64748b" font-size="11">{y_val:,.0f}</text>')

        # X轴时间标签
        x_ticks = []
        n_ticks = min(8, len(series))
        for i in range(n_ticks):
            idx = int(i * (len(series) - 1) / max(1, n_ticks - 1))
            ts = ts_list[idx]
            x, _ = points[idx] if idx < len(points) else (padding_l + plot_w, 0)
            label = datetime.fromtimestamp(ts).strftime("%H:%M:%S")
            x_ticks.append(f'<text x="{x:.1f}" y="{H-padding_b+20}" text-anchor="middle" fill="#64748b" font-size="11">{label}</text>')

        axes = [
            f'<line x1="{padding_l}" y1="{padding_t}" x2="{padding_l}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
            f'<line x1="{padding_l}" y1="{H-padding_b}" x2="{W-padding_r}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
        ]

        return f"""<svg viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet">
  <defs>
    <linearGradient id="qpsFill" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0%" stop-color="#3b82f6" stop-opacity="0.4"/>
      <stop offset="100%" stop-color="#3b82f6" stop-opacity="0.02"/>
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="{W}" height="{H}" fill="white"/>
  {''.join(y_ticks)}
  {''.join(x_ticks)}
  {''.join(axes)}
  {f'<path d="{fill_path}" fill="url(#qpsFill)"/>' if fill_path else ''}
  {f'<path d="{line_path}" fill="none" stroke="#3b82f6" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>' if line_path else ''}
  <text x="{W/2}" y="{H-8}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600">时间</text>
  <text x="20" y="{padding_t+plot_h/2}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600" transform="rotate(-90,20,{padding_t+plot_h/2})">QPS (req/s)</text>
</svg>"""

    def _errors_section(self, m: AggregatedMetrics) -> str:
        if m.errors.total_errors == 0:
            return '<section class="section"><h2>❌ 错误统计</h2><div class="empty" style="background:#d1fae5;color:#065f46;border-radius:8px;">🎉 没有错误！所有请求均成功。</div></section>'

        e = m.errors
        html = ['<section class="section"><h2>❌ 错误统计</h2>']

        # 状态码统计
        if e.by_status_code:
            html.append('<h3 style="margin:16px 0 12px;font-size:15px;">按状态码分布</h3>')
            html.append('<div class="table-wrap"><table><thead><tr><th>状态码</th><th>数量</th><th>占比</th><th>分布</th></tr></thead><tbody>')
            total = m.throughput.total_requests or 1
            for sc, cnt in sorted(e.by_status_code.items(), key=lambda x: -x[1]):
                pct = cnt / total * 100
                bar_pct = min(100, pct)
                color = "#10b981" if 200 <= sc < 400 else ("#f59e0b" if 400 <= sc < 500 else "#ef4444")
                html.append(f'<tr><td style="color:{color};font-weight:600;">{sc}</td><td>{cnt:,}</td><td>{pct:.4f}%</td><td style="text-align:left;"><div style="background:#f1f5f9;border-radius:4px;overflow:hidden;width:200px;"><div style="width:{bar_pct}%;background:{color};height:12px;"></div></div></td></tr>')
            html.append('</tbody></table></div>')

        # Top errors
        if e.top_errors:
            html.append('<h3 style="margin:16px 0 12px;font-size:15px;">Top 错误信息</h3>')
            html.append('<div class="table-wrap"><table><thead><tr><th>#</th><th>错误信息</th><th>数量</th><th>占比</th></tr></thead><tbody>')
            for i, (msg, cnt, pct) in enumerate(e.top_errors, 1):
                html.append(f'<tr><td>{i}</td><td style="text-align:left;font-family:monospace;font-size:12px;max-width:600px;word-break:break-all;">{msg}</td><td>{cnt:,}</td><td>{pct*100:.4f}%</td></tr>')
            html.append('</tbody></table></div>')

        html.append('</section>')
        return "".join(html)

    def _by_name_table(self, m: AggregatedMetrics) -> str:
        if not m.by_name:
            return '<div class="empty">暂无数据</div>'

        err_rate = m.errors.error_rate

        rows_html = []
        for name, lat in sorted(m.by_name.items(), key=lambda x: -x[1].count):
            cls = "bad" if err_rate > 0.05 else ("warn" if err_rate > 0.01 else "good")
            rows_html.append(
                f"<tr><td style='text-align:left;'>{name}</td>"
                f"<td>{lat.count:,}</td>"
                f"<td>{lat.min_ms:.2f}</td>"
                f"<td>{lat.p50_ms:.2f}</td>"
                f"<td>{lat.p90_ms:.2f}</td>"
                f"<td>{lat.p95_ms:.2f}</td>"
                f"<td>{lat.p99_ms:.2f}</td>"
                f"<td>{lat.p999_ms:.2f}</td>"
                f"<td>{lat.max_ms:.2f}</td>"
                f"<td>{lat.mean_ms:.2f}</td>"
                f'<td class="{cls}">{err_rate*100:.4f}%</td></tr>'
            )

        return f"""<table>
<thead><tr>
<th>请求名称</th><th>Count</th><th>Min(ms)</th><th>P50(ms)</th><th>P90(ms)</th>
<th>P95(ms)</th><th>P99(ms)</th><th>P99.9(ms)</th><th>Max(ms)</th><th>Mean(ms)</th><th>Err%</th>
</tr></thead>
<tbody>{"".join(rows_html)}</tbody>
</table>"""

    def _steps_detail(self, m: AggregatedMetrics) -> str:
        """生成按步骤的详细统计（可展开）"""
        if not hasattr(m, 'by_step') or not m.by_step:
            return '<div class="empty">暂无步骤数据</div>'

        steps_html = []
        for name, step in sorted(m.by_step.items(), key=lambda x: -x[1].total_requests):
            err_rate = 1.0 - step.success_rate
            status_cls = "good" if step.success_rate >= 0.99 else ("warn" if step.success_rate >= 0.95 else "bad")

            # 错误摘要
            error_summary = ""
            if step.errors and step.errors.top_errors:
                err_items = []
                for msg, cnt, pct in step.errors.top_errors[:5]:
                    short_msg = msg[:80] + "..." if len(msg) > 80 else msg
                    err_items.append(
                        f'<li><span class="err-cnt">{cnt}</span> {short_msg} '
                        f'<span class="err-pct">({pct*100:.2f}%)</span></li>'
                    )
                error_summary = f'<div class="step-errors"><h5>错误摘要 (Top)</h5><ul>{"".join(err_items)}</ul></div>'

            # 状态码分布（详细比例条）
            status_code_html = ""
            scd = getattr(step, "status_code_distribution", None) or (step.errors.by_status_code if step.errors else {})
            if scd:
                sc_rows = []
                for code, cnt in sorted(scd.items()):
                    share = cnt / step.total_requests * 100 if step.total_requests else 0
                    if str(code).startswith("2"):
                        sc_color = "#10b981"
                    elif str(code).startswith("3"):
                        sc_color = "#3b82f6"
                    elif str(code).startswith("4"):
                        sc_color = "#f59e0b"
                    elif str(code).startswith("5"):
                        sc_color = "#ef4444"
                    else:
                        sc_color = "#64748b"
                    sc_rows.append(
                        f'<div style="margin:4px 0;">'
                        f'<div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:2px;">'
                        f'<span><span style="display:inline-block;width:10px;height:10px;background:{sc_color};'
                        f'border-radius:2px;margin-right:6px;vertical-align:middle;"></span>'
                        f'<strong>HTTP {code}</strong></span>'
                        f'<span>{cnt:,} ({share:.1f}%)</span>'
                        f'</div>'
                        f'<div style="background:#f1f5f9;border-radius:3px;height:6px;overflow:hidden;">'
                        f'<div style="background:{sc_color};height:100%;width:{min(share,100):.1f}%;"></div>'
                        f'</div>'
                        f'</div>'
                    )
                status_code_html = f'<div class="step-status-codes"><h5>状态码分布</h5>{"".join(sc_rows)}</div>'

            def _pct_row(pm):
                if not pm or pm.count == 0:
                    return '<tr><td colspan="9" style="color:#94a3b8;text-align:center;">暂无数据</td></tr>'
                return (
                    f"<tr>"
                    f"<td>{pm.min_ms:.1f}</td>"
                    f"<td>{pm.p50_ms:.1f}</td>"
                    f"<td>{pm.p75_ms:.1f}</td>"
                    f"<td>{pm.p90_ms:.1f}</td>"
                    f"<td>{pm.p95_ms:.1f}</td>"
                    f"<td>{pm.p99_ms:.1f}</td>"
                    f"<td>{pm.p999_ms:.1f}</td>"
                    f"<td>{pm.max_ms:.1f}</td>"
                    f"<td>{pm.mean_ms:.1f}</td>"
                    f"</tr>"
                )

            lat_all = _pct_row(step.latency)
            lat_ok = _pct_row(getattr(step, "success_latency", None))
            lat_err = _pct_row(getattr(step, "failure_latency", None))

            tid = abs(hash(name)) % 10000000
            steps_html.append(f"""
<details class="step-card">
  <summary>
    <div class="step-header">
      <span class="step-name">{name}</span>
      <div class="step-metrics">
        <span class="metric"><strong>{step.total_requests:,}</strong><small>请求</small></span>
        <span class="metric"><strong>{step.success_rate*100:.2f}%</strong><small>成功率</small></span>
        <span class="metric"><strong>{step.overall_qps:.2f}</strong><small>QPS</small></span>
        <span class="metric"><strong>{step.latency.p50_ms:.1f}ms</strong><small>P50</small></span>
        <span class="metric"><strong>{step.latency.p95_ms:.1f}ms</strong><small>P95</small></span>
        <span class="metric"><strong>{step.latency.p99_ms:.1f}ms</strong><small>P99</small></span>
        <span class="metric status {status_cls}">{"OK" if step.success_rate >= 0.95 else "WARN"}</span>
      </div>
    </div>
  </summary>
  <div class="step-body">

    <div class="step-latency">
      <h5>延迟分布 (ms)
        <span style="display:inline-flex;margin-left:12px;gap:4px;font-weight:normal;">
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;background:#f8fafc;">
            <input type="radio" name="latTab{tid}" class="lat-tab-radio" value="all" checked style="display:none;">
            <span class="lat-tab-label" data-tab="all" data-tid="{tid}">全部 ({step.total_requests:,})</span>
          </label>
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;">
            <input type="radio" name="latTab{tid}" class="lat-tab-radio" value="success" style="display:none;">
            <span class="lat-tab-label success-label" data-tab="success" data-tid="{tid}">成功 ({step.total_success:,})</span>
          </label>
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;">
            <input type="radio" name="latTab{tid}" class="lat-tab-radio" value="failure" style="display:none;">
            <span class="lat-tab-label failure-label" data-tab="failure" data-tid="{tid}">失败 ({step.total_failures:,})</span>
          </label>
        </span>
      </h5>
      <table class="mini-table lat-tab-content" data-tab="all" data-tid="{tid}">
        <tr><th>Min</th><th>P50</th><th>P75</th><th>P90</th><th>P95</th><th>P99</th><th>P99.9</th><th>Max</th><th>Mean</th></tr>
        {lat_all}
      </table>
      <table class="mini-table lat-tab-content" data-tab="success" data-tid="{tid}" style="display:none;">
        <tr><th>Min</th><th>P50</th><th>P75</th><th>P90</th><th>P95</th><th>P99</th><th>P99.9</th><th>Max</th><th>Mean</th></tr>
        {lat_ok}
      </table>
      <table class="mini-table lat-tab-content" data-tab="failure" data-tid="{tid}" style="display:none;">
        <tr><th>Min</th><th>P50</th><th>P75</th><th>P90</th><th>P95</th><th>P99</th><th>P99.9</th><th>Max</th><th>Mean</th></tr>
        {lat_err}
      </table>
    </div>

    <div class="step-qps-section">
      <h5>QPS 时间线
        <span style="display:inline-flex;margin-left:12px;gap:4px;font-weight:normal;">
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;background:#f8fafc;">
            <input type="radio" name="qpsTab{tid}" class="qps-tab-radio" value="all" checked style="display:none;">
            <span class="qps-tab-label" data-tab="all" data-tid="{tid}">全部</span>
          </label>
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;">
            <input type="radio" name="qpsTab{tid}" class="qps-tab-radio" value="success" style="display:none;">
            <span class="qps-tab-label success-label" data-tab="success" data-tid="{tid}">成功</span>
          </label>
          <label style="cursor:pointer;font-size:12px;padding:2px 8px;border:1px solid #cbd5e1;border-radius:4px;">
            <input type="radio" name="qpsTab{tid}" class="qps-tab-radio" value="failure" style="display:none;">
            <span class="qps-tab-label failure-label" data-tab="failure" data-tid="{tid}">失败</span>
          </label>
        </span>
      </h5>
      <div class="step-qps-info">
        <span>平均: <strong>{step.overall_qps:.2f}/s</strong></span>
        <span>峰值: <strong>{step.peak_qps:.2f}/s</strong></span>
        <span>成功: <strong>{step.total_success:,}</strong></span>
        <span>失败: <strong style="color:{("#ef4444" if step.total_failures else "#94a3b8")};">{step.total_failures:,}</strong></span>
      </div>
      <div class="qps-tab-content" data-tab="all" data-tid="{tid}">{self._build_step_qps_sparkline_with_color(step.qps_series, "#667eea", f"a{tid}")}</div>
      <div class="qps-tab-content" data-tab="success" data-tid="{tid}" style="display:none;">{self._build_step_qps_sparkline_with_color(step.success_qps_series, "#10b981", f"o{tid}")}</div>
      <div class="qps-tab-content" data-tab="failure" data-tid="{tid}" style="display:none;">{self._build_step_qps_sparkline_with_color(step.failure_qps_series, "#ef4444", f"e{tid}")}</div>
    </div>

    {status_code_html}
    {error_summary}
  </div>
</details>
""")

        tab_js = """
<script>
(function(){
  function bindTab(radioSel, contentSel, labelClass){
    document.querySelectorAll(radioSel).forEach(function(r){
      r.addEventListener('change', function(){
        var tab = this.value;
        var m = this.name.match(/(\\d+)/);
        var tid = m ? m[1] : '';
        document.querySelectorAll(contentSel + '[data-tid=\"' + tid + '\"]').forEach(function(el){
          el.style.display = (el.dataset.tab === tab) ? '' : 'none';
        });
        document.querySelectorAll(labelClass + '[data-tid=\"' + tid + '\"]').forEach(function(lbl){
          if (lbl.dataset.tab === tab) {
            lbl.parentElement.style.background = '#f8fafc';
            lbl.parentElement.style.border = '1px solid #94a3b8';
            lbl.parentElement.style.fontWeight = '600';
          } else {
            lbl.parentElement.style.background = '';
            lbl.parentElement.style.border = '1px solid #cbd5e1';
            lbl.parentElement.style.fontWeight = '';
          }
        });
      });
    });
    document.querySelectorAll(radioSel + ':checked').forEach(function(r){
      r.dispatchEvent(new Event('change'));
    });
  }
  function init(){
    bindTab('.lat-tab-radio', '.lat-tab-content', '.lat-tab-label');
    bindTab('.qps-tab-radio', '.qps-tab-content', '.qps-tab-label');
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
</script>
<style>
.success-label{color:#10b981;}
.failure-label{color:#ef4444;}
</style>
"""
        return "".join(steps_html) + tab_js

    def _build_step_qps_sparkline_with_color(
        self, qps_series, color, grad_id
    ):
        if not qps_series:
            return '<div style="color:#94a3b8;padding:20px;text-align:center;font-size:12px;">暂无数据</div>'
        width = 600
        height = 80
        padding = 10
        values = [q for _, q in qps_series]
        max_v = max(values) or 1
        n = len(values)
        if n <= 1:
            return '<div style="color:#94a3b8;padding:12px;text-align:center;font-size:12px;">数据点不足</div>'
        points = []
        for i, v in enumerate(values):
            x = padding + (width - 2 * padding) * i / (n - 1)
            y = height - padding - (height - 2 * padding) * v / max_v
            points.append(f"{x:.1f},{y:.1f}")
        path_d = "M " + " L ".join(points)
        area_d = path_d + f" L {width-padding:.1f},{height-padding:.1f} L {padding:.1f},{height-padding:.1f} Z"
        return f"""
<svg class="sparkline" viewBox="0 0 {width} {height}" preserveAspectRatio="none">
  <defs>
    <linearGradient id="{grad_id}" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="{color}" stop-opacity="0.3"/>
      <stop offset="100%" stop-color="{color}" stop-opacity="0.05"/>
    </linearGradient>
  </defs>
  <path d="{area_d}" fill="url(#{grad_id})"/>
  <path d="{path_d}" fill="none" stroke="{color}" stroke-width="1.5"/>
</svg>
"""

    def _build_step_qps_sparkline(self, qps_series):
        """生成步骤QPS的迷你折线图（sparkline）- 兼容老接口"""
        return self._build_step_qps_sparkline_with_color(qps_series, "#667eea", "compatGrad")

    def _status_section(self, m: AggregatedMetrics) -> str:
        if not m.by_status:
            return ""

        total = sum(m.by_status.values()) or 1
        rows = []
        color_map = {
            "success": "#10b981",
            "failure": "#f59e0b",
            "error": "#ef4444",
            "timeout": "#f97316",
            "assertion_failed": "#8b5cf6",
        }
        for status, cnt in sorted(m.by_status.items(), key=lambda x: -x[1]):
            color = color_map.get(status, "#64748b")
            pct = cnt / total * 100
            rows.append(f'<div style="margin:8px 0;"><div style="display:flex;justify-content:space-between;margin-bottom:4px;"><span><span style="display:inline-block;width:12px;height:12px;background:{color};border-radius:3px;margin-right:8px;"></span>{status}</span><span>{cnt:,} ({pct:.2f}%)</span></div><div style="background:#f1f5f9;border-radius:4px;height:10px;overflow:hidden;"><div style="background:{color};height:100%;width:{pct}%;"></div></div></div>')

        return f"""<section class="section">
  <h2>📊 请求状态分布</h2>
  {"".join(rows)}
</section>"""

    def _scenario_section(self, m: AggregatedMetrics) -> str:
        """场景级统计 section"""
        if not m.scenario or m.scenario.total_iterations == 0:
            return ""

        sc = m.scenario
        html = ['<section class="section"><h2>🔄 场景迭代统计</h2>']
        html.append('<div class="table-wrap"><table><thead><tr><th>场景名称</th><th>迭代总数</th><th>成功</th><th>失败</th><th>成功率</th>')
        html.append('<th>Min(ms)</th><th>P50(ms)</th><th>P95(ms)</th><th>P99(ms)</th><th>Max(ms)</th><th>Mean(ms)</th></tr></thead><tbody>')

        # 总体场景统计
        total_sr = sc.success_iterations / sc.total_iterations if sc.total_iterations else 1.0
        cls = "good" if total_sr >= 0.99 else ("warn" if total_sr >= 0.95 else "bad")
        html.append(
            f"<tr><td style='text-align:left;font-weight:600;'>[整体]</td>"
            f"<td>{sc.total_iterations:,}</td>"
            f"<td>{sc.success_iterations:,}</td>"
            f"<td>{sc.failed_iterations:,}</td>"
            f'<td class="{cls}">{total_sr*100:.4f}%</td>'
            f"<td>{sc.latency.min_ms:.2f}</td>"
            f"<td>{sc.latency.p50_ms:.2f}</td>"
            f"<td>{sc.latency.p95_ms:.2f}</td>"
            f"<td>{sc.latency.p99_ms:.2f}</td>"
            f"<td>{sc.latency.max_ms:.2f}</td>"
            f"<td>{sc.latency.mean_ms:.2f}</td></tr>"
        )

        # 按场景分组统计
        for name, lat in sorted(sc.by_scenario.items(), key=lambda x: -x[1].count):
            scene_total = lat.count
            # 这个场景的成功率（近似，用场景级统计）
            scene_sr = sc.success_iterations / max(1, sc.total_iterations)
            cls = "good" if scene_sr >= 0.99 else ("warn" if scene_sr >= 0.95 else "bad")
            html.append(
                f"<tr><td style='text-align:left;padding-left:24px;'>{name}</td>"
                f"<td>{lat.count:,}</td>"
                f"<td>-</td><td>-</td>"
                f'<td class="{cls}">{scene_sr*100:.4f}%</td>'
                f"<td>{lat.min_ms:.2f}</td>"
                f"<td>{lat.p50_ms:.2f}</td>"
                f"<td>{lat.p95_ms:.2f}</td>"
                f"<td>{lat.p99_ms:.2f}</td>"
                f"<td>{lat.max_ms:.2f}</td>"
                f"<td>{lat.mean_ms:.2f}</td></tr>"
            )

        html.append('</tbody></table></div></section>')
        return "".join(html)

    def _parameter_section(self, m: AggregatedMetrics) -> str:
        """参数使用统计 section（CSV 数据池使用情况等）"""
        if not m.csv_stats and not m.parameter_stats:
            return ""

        html = ['<section class="section">']
        html.append("<h2>📊 参数使用统计</h2>")

        # CSV 参数统计
        if m.csv_stats:
            html.append('<h3 style="margin-top:16px;">CSV 数据池</h3>')
            html.append('<div class="table-wrap"><table><thead><tr>')
            html.append("<th>参数名</th><th>读取模式</th><th>总行数</th><th>覆盖率 (max)</th>")
            html.append("<th>循环次数</th><th>循环复用</th><th>调用总次数</th><th>Worker数</th>")
            html.append("</tr></thead><tbody>")

            for s in m.csv_stats:
                name = s.get("name", "?")
                mode = s.get("read_mode") or s.get("mode", "?")
                total_rows = s.get("total_rows", 0)
                rows_used = s.get("rows_used", 0) or s.get("rows_used_max", 0)
                loop_count = s.get("loop_count", 0)
                recycled = s.get("recycled", False) or s.get("any_recycled", False)
                call_count = s.get("call_count", 0) or s.get("total_call_count", 0)
                workers_using = s.get("workers_using", 0)
                coverage_pct = s.get("coverage_pct")
                if coverage_pct is None:
                    coverage_pct = round((rows_used / max(1, total_rows)) * 100, 2) if total_rows else 0
                recycled_tag = '<span class="badge warn">是</span>' if recycled else '<span class="badge good">否</span>'
                coverage_color = "#10b981" if coverage_pct >= 80 else ("#f59e0b" if coverage_pct >= 50 else "#ef4444")
                if recycled:
                    coverage_color = "#f59e0b"

                # 使用比例条
                usage_bar = (
                    f'<div style="width:150px;height:10px;background:#eee;border-radius:4px;overflow:hidden;">'
                    f'<div style="width:{min(coverage_pct, 100):.1f}%;height:100%;'
                    f'background:{coverage_color};"></div></div>'
                    f'<div style="font-size:12px;color:#666;">{rows_used}/{total_rows} ({coverage_pct:.1f}%)</div>'
                )

                html.append(
                    f"<tr>"
                    f"<td style='text-align:left;font-weight:600;'>{name}</td>"
                    f"<td>{mode}</td>"
                    f"<td>{total_rows:,}</td>"
                    f"<td>{usage_bar}</td>"
                    f"<td>{loop_count}</td>"
                    f"<td>{recycled_tag}</td>"
                    f"<td>{call_count:,}</td>"
                    f"<td>{workers_using}</td>"
                    f"</tr>"
                )

            html.append("</tbody></table></div>")

            # Worker 使用量详情（每个 CSV 展开显示）
            for s in m.csv_stats:
                name = s.get("name", "?")
                call_per_w = s.get("call_count_per_worker", {})
                rows_per_w = s.get("rows_used_per_worker", {})
                loop_per_w = s.get("loop_count_per_worker", {})
                if not call_per_w:
                    continue
                html.append(
                    f'<details class="worker-details" style="margin-top:8px;">'
                    f'<summary style="cursor:pointer;color:#475569;padding:4px 0;">'
                    f'📋 {name} - 各 Worker 使用明细 (点击展开)</summary>'
                )
                html.append(
                    '<div class="table-wrap" style="margin-top:8px;">'
                    '<table style="font-size:13px;"><thead><tr>'
                    '<th>Worker ID</th><th>调用次数</th><th>使用行数</th><th>循环次数</th>'
                    '</tr></thead><tbody>'
                )
                for wid in sorted(call_per_w.keys()):
                    html.append(
                        f"<tr>"
                        f"<td style='text-align:left;'>{wid}</td>"
                        f"<td>{call_per_w.get(wid, 0):,}</td>"
                        f"<td>{rows_per_w.get(wid, 0):,}</td>"
                        f"<td>{loop_per_w.get(wid, 0)}</td>"
                        f"</tr>"
                    )
                html.append("</tbody></table></div></details>")

        # 其他参数统计（计数器、序列等）
        if m.parameter_stats:
            # 按参数名聚合，显示每个 worker 的情况
            param_by_name: Dict[str, list] = {}
            for p in m.parameter_stats:
                nm = p.get("name", "?")
                if p.get("type") == "csv":
                    continue
                if nm not in param_by_name:
                    param_by_name[nm] = []
                param_by_name[nm].append(p)

            if param_by_name:
                html.append('<h3 style="margin-top:24px;">其他参数</h3>')
                html.append('<div class="table-wrap"><table><thead><tr>')
                html.append("<th>参数名</th><th>类型</th><th>总调用次数</th><th>Worker分布</th><th>当前值/说明</th>")
                html.append("</tr></thead><tbody>")

                for nm, entries in param_by_name.items():
                    ptype = entries[0].get("type", "?")
                    total_calls = sum(e.get("call_count", 0) for e in entries)
                    current = entries[0].get("current_value", "") or entries[0].get("description", "")
                    worker_dist = ", ".join(
                        f"{e.get('worker_id', '?')}:{e.get('call_count', 0)}"
                        for e in sorted(entries, key=lambda x: x.get("worker_id", ""))
                    )
                    if len(worker_dist) > 80:
                        worker_dist = worker_dist[:77] + "..."
                    html.append(
                        f"<tr>"
                        f"<td style='text-align:left;font-weight:600;'>{nm}</td>"
                        f"<td>{ptype}</td>"
                        f"<td>{total_calls:,}</td>"
                        f"<td style='text-align:left;font-size:12px;color:#666;'>{worker_dist}</td>"
                        f"<td style='text-align:left;'>{current}</td>"
                        f"</tr>"
                    )

                html.append("</tbody></table></div>")

        html.append("</section>")
        return "".join(html)
