"""HTML报告输出器

生成包含可视化图表的独立HTML报告文件。
使用纯CSS + SVG绘制图表，不依赖外部资源，可直接离线打开。

包含的图表：
1. QPS 时序折线图（SVG）
2. 延迟分布直方图（SVG）
3. 延迟分位甘特图
4. 状态码饼图
5. 核心指标卡片
"""
from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from ..stats.aggregator import AggregatedMetrics


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<div class="container">
  <header class="header">
    <h1>📊 {title}</h1>
    <p class="subtitle">生成时间: {generated_at}</p>
  </header>

  <section class="cards">
    {summary_cards}
  </section>

  <section class="section">
    <h2>⏱️ 延迟分布</h2>
    <div class="chart-container">
      {latency_chart}
    </div>
    <div class="latency-table">
      {latency_table}
    </div>
  </section>

  <section class="section">
    <h2>📈 QPS 时序</h2>
    <div class="chart-container">
      {qps_chart}
    </div>
  </section>

  {errors_section}

  <section class="section">
    <h2>📋 请求明细</h2>
    <div class="table-wrap">
      {by_name_table}
    </div>
  </section>

  {status_section}

  <footer class="footer">
    <p>Generated by <strong>load_tester</strong> v1.0.0</p>
  </footer>
</div>
</body>
</html>"""

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
    "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
  background: #f0f2f5;
  color: #333;
  line-height: 1.6;
}
.container { max-width: 1200px; margin: 0 auto; padding: 24px; }

.header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 32px;
  border-radius: 16px;
  margin-bottom: 24px;
  box-shadow: 0 4px 20px rgba(102, 126, 234, 0.3);
}
.header h1 { font-size: 28px; margin-bottom: 8px; }
.header .subtitle { opacity: 0.9; font-size: 14px; }

.cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 16px;
  margin-bottom: 24px;
}
.card {
  background: white;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
}
.card-label { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
.card-value { font-size: 28px; font-weight: 700; margin-top: 8px; }
.card-sub { font-size: 12px; color: #666; margin-top: 4px; }
.card.green .card-value { color: #10b981; }
.card.red .card-value { color: #ef4444; }
.card.blue .card-value { color: #3b82f6; }
.card.purple .card-value { color: #8b5cf6; }
.card.amber .card-value { color: #f59e0b; }
.card.cyan .card-value { color: #06b6d4; }

.section {
  background: white;
  border-radius: 16px;
  padding: 24px;
  margin-bottom: 24px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.08);
}
.section h2 {
  font-size: 18px;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 2px solid #f0f2f5;
}

.chart-container { width: 100%; overflow-x: auto; }
.chart-container svg { width: 100%; max-width: 100%; height: auto; }

.latency-table { margin-top: 20px; overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
th, td {
  padding: 10px 12px;
  text-align: right;
  border-bottom: 1px solid #f0f2f5;
}
th:first-child, td:first-child { text-align: left; }
th {
  background: #f8fafc;
  font-weight: 600;
  color: #475569;
  position: sticky;
  top: 0;
}
tr:hover td { background: #f8fafc; }

.table-wrap { overflow-x: auto; }

.footer {
  text-align: center;
  color: #94a3b8;
  padding: 20px;
  font-size: 12px;
}

.good { color: #10b981; font-weight: 600; }
.warn { color: #f59e0b; font-weight: 600; }
.bad { color: #ef4444; font-weight: 600; }

.empty { text-align: center; color: #94a3b8; padding: 40px; }
"""


class HtmlReporter:
    """HTML报告生成器"""

    def __init__(self):
        pass

    def report(
        self,
        metrics: AggregatedMetrics,
        output_path: Union[str, Path],
        title: str = "Load Test Report",
    ) -> None:
        """生成HTML报告并写入文件"""
        html = self._build_html(metrics, title)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

    def _build_html(self, m: AggregatedMetrics, title: str) -> str:
        # 概要卡片
        summary_cards = self._summary_cards(m)

        # 延迟图表
        latency_chart = self._build_latency_histogram(m)
        latency_table = self._latency_table(m)

        # QPS图表
        qps_chart = self._build_qps_chart(m)

        # 错误部分
        errors_section = self._errors_section(m)

        # 按名称分组
        by_name_table = self._by_name_table(m)

        # 状态分布
        status_section = self._status_section(m)

        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return _HTML_TEMPLATE.format(
            title=title,
            generated_at=generated_at,
            css=_CSS,
            summary_cards=summary_cards,
            latency_chart=latency_chart,
            latency_table=latency_table,
            qps_chart=qps_chart,
            errors_section=errors_section,
            by_name_table=by_name_table,
            status_section=status_section,
        )

    def _card(self, label: str, value: str, sub: str = "", color: str = "") -> str:
        color_cls = f" {color}" if color else ""
        sub_html = f'<div class="card-sub">{sub}</div>' if sub else ""
        return f'<div class="card{color_cls}"><div class="card-label">{label}</div><div class="card-value">{value}</div>{sub_html}</div>'

    def _summary_cards(self, m: AggregatedMetrics) -> str:
        total = m.throughput.total_requests
        success = m.throughput.total_success
        errors = m.errors.total_errors
        sr = success / total if total else 1.0
        duration = m.duration_seconds

        sr_color = "green" if sr >= 0.99 else ("amber" if sr >= 0.95 else "red")
        err_color = "green" if errors == 0 else ("amber" if m.errors.error_rate < 0.05 else "red")

        cards = [
            self._card("总请求数", f"{total:,}", f"Duration: {duration:.1f}s", "blue"),
            self._card("成功率", f"{sr*100:.2f}%", f"{success:,} 成功", sr_color),
            self._card("失败数", f"{errors:,}", f"错误率: {m.errors.error_rate*100:.4f}%", err_color),
            self._card("平均QPS", f"{m.throughput.overall_qps:,.1f}", f"峰值: {m.throughput.peak_qps:,.1f}", "purple"),
            self._card("P50延迟", f"{m.overall.p50_ms:.2f}ms", f"平均: {m.overall.mean_ms:.2f}ms", "cyan"),
            self._card("P99延迟", f"{m.overall.p99_ms:.2f}ms", f"最大: {m.overall.max_ms:.2f}ms", "amber"),
        ]
        return "\n".join(cards)

    def _build_latency_histogram(self, m: AggregatedMetrics) -> str:
        """绘制延迟分布直方图（SVG）"""
        snap = m.histogram_snapshot
        if not snap or not snap.buckets:
            return '<div class="empty">暂无数据</div>'

        buckets = [(bs / 1_000_000, cnt) for bs, cnt in snap.buckets if cnt > 0]
        if not buckets:
            return '<div class="empty">暂无数据</div>'

        max_count = max(c for _, c in buckets)
        max_lat = max(ms for ms, _ in buckets)
        min_lat = min(ms for ms, _ in buckets) if buckets else 0

        W, H = 900, 300
        padding_l, padding_r, padding_t, padding_b = 70, 30, 30, 60
        plot_w = W - padding_l - padding_r
        plot_h = H - padding_t - padding_b
        bar_w = max(2, plot_w / max(1, len(buckets)) - 1)

        x_ratio = plot_w / max(1e-9, (max_lat - min_lat)) if max_lat != min_lat else 1
        y_ratio = plot_h / max(1, max_count)

        # 生成柱子
        bars = []
        for i, (ms_val, cnt) in enumerate(buckets):
            x = padding_l + (ms_val - min_lat) * x_ratio if max_lat != min_lat else padding_l + i * (bar_w + 1)
            h = max(1, cnt * y_ratio)
            y = padding_t + plot_h - h
            # 颜色随高度渐变
            pct = cnt / max_count
            r = int(100 + pct * 155)
            g = int(180 - pct * 60)
            b = int(255 - pct * 100)
            color = f"rgb({r},{g},{b})"
            bars.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{h:.1f}" fill="{color}"><title>{ms_val:.2f}ms: {cnt}</title></rect>')

        # Y轴刻度
        y_ticks = []
        for i in range(5):
            y_val = max_count * i / 4
            y = padding_t + plot_h - y_val * y_ratio
            y_ticks.append(f'<line x1="{padding_l}" y1="{y:.1f}" x2="{W-padding_r}" y2="{y:.1f}" stroke="#e2e8f0" stroke-dasharray="4"/>')
            y_ticks.append(f'<text x="{padding_l-8}" y="{y+4:.1f}" text-anchor="end" fill="#64748b" font-size="11">{int(y_val)}</text>')

        # X轴刻度
        x_ticks = []
        n_ticks = 8
        for i in range(n_ticks + 1):
            ms_val = min_lat + (max_lat - min_lat) * i / n_ticks if max_lat != min_lat else min_lat
            x = padding_l + plot_w * i / n_ticks
            label = f"{ms_val:.1f}ms" if ms_val < 1000 else f"{ms_val/1000:.2f}s"
            x_ticks.append(f'<text x="{x:.1f}" y="{H-padding_b+20}" text-anchor="middle" fill="#64748b" font-size="11">{label}</text>')

        # 轴
        axes = [
            f'<line x1="{padding_l}" y1="{padding_t}" x2="{padding_l}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
            f'<line x1="{padding_l}" y1="{H-padding_b}" x2="{W-padding_r}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
        ]

        return f"""<svg viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet">
  <rect x="0" y="0" width="{W}" height="{H}" fill="white"/>
  {''.join(y_ticks)}
  {''.join(x_ticks)}
  {''.join(axes)}
  {''.join(bars)}
  <text x="{W/2}" y="{H-8}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600">延迟 (ms)</text>
  <text x="20" y="{padding_t+plot_h/2}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600" transform="rotate(-90,20,{padding_t+plot_h/2})">请求数</text>
</svg>"""

    def _latency_table(self, m: AggregatedMetrics) -> str:
        lat = m.overall
        rows = [
            ("总样本数", lat.count),
            ("最小值", f"{lat.min_ms:.3f} ms"),
            ("P50 中位数", f"{lat.p50_ms:.3f} ms"),
            ("P75", f"{lat.p75_ms:.3f} ms"),
            ("P90", f"{lat.p90_ms:.3f} ms"),
            ("P95", f"{lat.p95_ms:.3f} ms"),
            ("P99", f"{lat.p99_ms:.3f} ms"),
            ("P99.9", f"{lat.p999_ms:.3f} ms"),
            ("P99.99", f"{lat.p9999_ms:.3f} ms"),
            ("最大值", f"{lat.max_ms:.3f} ms"),
            ("平均值", f"{lat.mean_ms:.3f} ms"),
            ("标准差", f"{lat.stddev_ms:.3f} ms"),
        ]
        # 每列4个，生成3列布局
        per_col = 4
        cols = []
        for c in range((len(rows) + per_col - 1) // per_col):
            rows_slice = rows[c * per_col : (c + 1) * per_col]
            col_html = "<table><thead><tr><th>指标</th><th>值</th></tr></thead><tbody>"
            for k, v in rows_slice:
                col_html += f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>"
            col_html += "</tbody></table>"
            cols.append(col_html)
        style = f'display:grid; grid-template-columns: repeat({len(cols)}, 1fr); gap:16px;'
        return f'<div style="{style}">{"".join(cols)}</div>'

    def _build_qps_chart(self, m: AggregatedMetrics) -> str:
        """绘制QPS时序折线图（SVG）"""
        series = m.throughput.qps_series
        if not series:
            return '<div class="empty">暂无数据</div>'

        W, H = 900, 280
        padding_l, padding_r, padding_t, padding_b = 70, 30, 30, 60
        plot_w = W - padding_l - padding_r
        plot_h = H - padding_t - padding_b

        ts_list = [t for t, _ in series]
        qps_list = [q for _, q in series]
        min_ts, max_ts = min(ts_list), max(ts_list)
        max_qps = max(qps_list) if qps_list else 0
        max_qps = max_qps * 1.1 if max_qps > 0 else 1

        x_ratio = plot_w / max(1e-9, (max_ts - min_ts)) if max_ts != min_ts else 1
        y_ratio = plot_h / max(1, max_qps)

        # 生成折线点
        points = []
        for i, (ts, qps) in enumerate(series):
            x = padding_l + (ts - min_ts) * x_ratio if max_ts != min_ts else padding_l + i * plot_w / max(1, len(series) - 1)
            y = padding_t + plot_h - qps * y_ratio
            points.append((x, y))

        # 填充区域（折线下方渐变）
        if len(points) >= 2:
            fill_path = f'M {points[0][0]:.1f} {padding_t+plot_h:.1f} '
            fill_path += " ".join(f"L {x:.1f} {y:.1f}" for x, y in points)
            fill_path += f" L {points[-1][0]:.1f} {padding_t+plot_h:.1f} Z"
        else:
            fill_path = ""

        line_path = ""
        if len(points) >= 2:
            line_path = f"M {points[0][0]:.1f} {points[0][1]:.1f} "
            line_path += " ".join(f"L {x:.1f} {y:.1f}" for x, y in points[1:])

        # Y轴
        y_ticks = []
        for i in range(5):
            y_val = max_qps * i / 4
            y = padding_t + plot_h - y_val * y_ratio
            y_ticks.append(f'<line x1="{padding_l}" y1="{y:.1f}" x2="{W-padding_r}" y2="{y:.1f}" stroke="#e2e8f0" stroke-dasharray="4"/>')
            y_ticks.append(f'<text x="{padding_l-8}" y="{y+4:.1f}" text-anchor="end" fill="#64748b" font-size="11">{y_val:,.0f}</text>')

        # X轴时间标签
        x_ticks = []
        n_ticks = min(8, len(series))
        for i in range(n_ticks):
            idx = int(i * (len(series) - 1) / max(1, n_ticks - 1))
            ts = ts_list[idx]
            x, _ = points[idx] if idx < len(points) else (padding_l + plot_w, 0)
            label = datetime.fromtimestamp(ts).strftime("%H:%M:%S")
            x_ticks.append(f'<text x="{x:.1f}" y="{H-padding_b+20}" text-anchor="middle" fill="#64748b" font-size="11">{label}</text>')

        axes = [
            f'<line x1="{padding_l}" y1="{padding_t}" x2="{padding_l}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
            f'<line x1="{padding_l}" y1="{H-padding_b}" x2="{W-padding_r}" y2="{H-padding_b}" stroke="#cbd5e1" stroke-width="2"/>',
        ]

        return f"""<svg viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid meet">
  <defs>
    <linearGradient id="qpsFill" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0%" stop-color="#3b82f6" stop-opacity="0.4"/>
      <stop offset="100%" stop-color="#3b82f6" stop-opacity="0.02"/>
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="{W}" height="{H}" fill="white"/>
  {''.join(y_ticks)}
  {''.join(x_ticks)}
  {''.join(axes)}
  {f'<path d="{fill_path}" fill="url(#qpsFill)"/>' if fill_path else ''}
  {f'<path d="{line_path}" fill="none" stroke="#3b82f6" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>' if line_path else ''}
  <text x="{W/2}" y="{H-8}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600">时间</text>
  <text x="20" y="{padding_t+plot_h/2}" text-anchor="middle" fill="#475569" font-size="12" font-weight="600" transform="rotate(-90,20,{padding_t+plot_h/2})">QPS (req/s)</text>
</svg>"""

    def _errors_section(self, m: AggregatedMetrics) -> str:
        if m.errors.total_errors == 0:
            return '<section class="section"><h2>❌ 错误统计</h2><div class="empty" style="background:#d1fae5;color:#065f46;border-radius:8px;">🎉 没有错误！所有请求均成功。</div></section>'

        e = m.errors
        html = ['<section class="section"><h2>❌ 错误统计</h2>']

        # 状态码统计
        if e.by_status_code:
            html.append('<h3 style="margin:16px 0 12px;font-size:15px;">按状态码分布</h3>')
            html.append('<div class="table-wrap"><table><thead><tr><th>状态码</th><th>数量</th><th>占比</th><th>分布</th></tr></thead><tbody>')
            total = m.throughput.total_requests or 1
            for sc, cnt in sorted(e.by_status_code.items(), key=lambda x: -x[1]):
                pct = cnt / total * 100
                bar_pct = min(100, pct)
                color = "#10b981" if 200 <= sc < 400 else ("#f59e0b" if 400 <= sc < 500 else "#ef4444")
                html.append(f'<tr><td style="color:{color};font-weight:600;">{sc}</td><td>{cnt:,}</td><td>{pct:.4f}%</td><td style="text-align:left;"><div style="background:#f1f5f9;border-radius:4px;overflow:hidden;width:200px;"><div style="width:{bar_pct}%;background:{color};height:12px;"></div></div></td></tr>')
            html.append('</tbody></table></div>')

        # Top errors
        if e.top_errors:
            html.append('<h3 style="margin:16px 0 12px;font-size:15px;">Top 错误信息</h3>')
            html.append('<div class="table-wrap"><table><thead><tr><th>#</th><th>错误信息</th><th>数量</th><th>占比</th></tr></thead><tbody>')
            for i, (msg, cnt, pct) in enumerate(e.top_errors, 1):
                html.append(f'<tr><td>{i}</td><td style="text-align:left;font-family:monospace;font-size:12px;max-width:600px;word-break:break-all;">{msg}</td><td>{cnt:,}</td><td>{pct*100:.4f}%</td></tr>')
            html.append('</tbody></table></div>')

        html.append('</section>')
        return "".join(html)

    def _by_name_table(self, m: AggregatedMetrics) -> str:
        if not m.by_name:
            return '<div class="empty">暂无数据</div>'

        err_rate = m.errors.error_rate

        rows_html = []
        for name, lat in sorted(m.by_name.items(), key=lambda x: -x[1].count):
            cls = "bad" if err_rate > 0.05 else ("warn" if err_rate > 0.01 else "good")
            rows_html.append(
                f"<tr><td style='text-align:left;'>{name}</td>"
                f"<td>{lat.count:,}</td>"
                f"<td>{lat.min_ms:.2f}</td>"
                f"<td>{lat.p50_ms:.2f}</td>"
                f"<td>{lat.p90_ms:.2f}</td>"
                f"<td>{lat.p95_ms:.2f}</td>"
                f"<td>{lat.p99_ms:.2f}</td>"
                f"<td>{lat.p999_ms:.2f}</td>"
                f"<td>{lat.max_ms:.2f}</td>"
                f"<td>{lat.mean_ms:.2f}</td>"
                f'<td class="{cls}">{err_rate*100:.4f}%</td></tr>'
            )

        return f"""<table>
<thead><tr>
<th>请求名称</th><th>Count</th><th>Min(ms)</th><th>P50(ms)</th><th>P90(ms)</th>
<th>P95(ms)</th><th>P99(ms)</th><th>P99.9(ms)</th><th>Max(ms)</th><th>Mean(ms)</th><th>Err%</th>
</tr></thead>
<tbody>{"".join(rows_html)}</tbody>
</table>"""

    def _status_section(self, m: AggregatedMetrics) -> str:
        if not m.by_status:
            return ""

        total = sum(m.by_status.values()) or 1
        rows = []
        color_map = {
            "success": "#10b981",
            "failure": "#f59e0b",
            "error": "#ef4444",
            "timeout": "#f97316",
            "assertion_failed": "#8b5cf6",
        }
        for status, cnt in sorted(m.by_status.items(), key=lambda x: -x[1]):
            color = color_map.get(status, "#64748b")
            pct = cnt / total * 100
            rows.append(f'<div style="margin:8px 0;"><div style="display:flex;justify-content:space-between;margin-bottom:4px;"><span><span style="display:inline-block;width:12px;height:12px;background:{color};border-radius:3px;margin-right:8px;"></span>{status}</span><span>{cnt:,} ({pct:.2f}%)</span></div><div style="background:#f1f5f9;border-radius:4px;height:10px;overflow:hidden;"><div style="background:{color};height:100%;width:{pct}%;"></div></div></div>')

        return f"""<section class="section">
  <h2>📊 请求状态分布</h2>
  {"".join(rows)}
</section>"""
